<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnhanceSure.Application\EnhanceSure.Application.csproj" />
    <ProjectReference Include="..\EnhanceSure.Infrastructure\EnhanceSure.Infrastructure.csproj" />
    <ProjectReference Include="..\EnhanceSure.Persistance\EnhanceSure.Persistance.csproj" />
  </ItemGroup>

</Project>
