<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Enhancesure.Domain\Enhancesure.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Persistances\" />
    <Folder Include="DTOs\" />
    <Folder Include="Profiles\" />
    <Folder Include="Shared\Responses\" />
    <Folder Include="Shared\Requests\" />
  </ItemGroup>

</Project>
